FROM python:3.11

SHELL ["/bin/bash", "-c"]

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install --upgrade pip

WORKDIR /am

RUN mkdir /am/static && mkdir /am/media

RUN pip install poetry
RUN poetry config virtualenvs.create false --local

COPY . .

RUN poetry install

RUN  python manage.py makemigrations &&  \
     python manage.py migrate &&  \
     python manage.py create_superuser &&  \
     python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn","-b","0.0.0.0:8000","NKO.wsgi:application"]