# Generated by Django 3.2.5 on 2023-07-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=255, verbose_name='Идентификатор поля')),
                ('name_field', models.CharField(default='Дата', max_length=255, verbose_name='Имя поля')),
                ('time', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='FieldStartFinishTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=255, verbose_name='Идентификатор поля')),
                ('name_field', models.CharField(default='Начало-Конец время', max_length=255, verbose_name='Имя поля')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('finish', models.DateTimeField(verbose_name='Конец')),
            ],
        ),
        migrations.CreateModel(
            name='FieldText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=255, verbose_name='Идентификатор поля')),
                ('name_field', models.CharField(default='Текст', max_length=255, verbose_name='Имя поля')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTextarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=255, verbose_name='Идентификатор поля')),
                ('name_field', models.CharField(default='Большой текс', max_length=255, verbose_name='Имя поля')),
                ('textarea', models.TextField(verbose_name='Большой текст')),
            ],
        ),
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название проекта')),
                ('structure_project', models.JSONField(verbose_name='структура проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название этапа')),
                ('structure_step', models.JSONField(verbose_name='структура этапа')),
                ('next_step', models.IntegerField(blank=True, verbose_name='id следующего этапа')),
                ('date_create', models.DateTimeField(verbose_name='Дата создание')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала работы')),
                ('date_end', models.DateTimeField(verbose_name='Дата конца работы')),
                ('SF_time', models.ManyToManyField(blank=True, to='api_for_front.FieldStartFinishTime', verbose_name='Срок')),
                ('date', models.ManyToManyField(blank=True, to='api_for_front.FieldDate', verbose_name='Дата')),
                ('text', models.ManyToManyField(blank=True, to='api_for_front.FieldText', verbose_name='Текст')),
                ('textarea', models.ManyToManyField(blank=True, to='api_for_front.FieldTextarea', verbose_name='Большой текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('path_file', models.FileField(upload_to='images/%Y/%m.%d/', verbose_name='Файл')),
                ('link_main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_for_front.mainproject', verbose_name='Объект привязки')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('path_file', models.FileField(upload_to='file/%Y/%m.%d/', verbose_name='Файл')),
                ('link_main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_for_front.mainproject', verbose_name='Объект привязки')),
            ],
        ),
        migrations.AddField(
            model_name='mainproject',
            name='stages',
            field=models.ManyToManyField(related_name='base', to='api_for_front.Step', verbose_name='Список Этапов'),
        ),
        migrations.AddField(
            model_name='mainproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
    ]
