# Generated by Django 3.2.5 on 2023-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddate',
            name='identify',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор поля'),
        ),
        migrations.AlterField(
            model_name='fielddate',
            name='time',
            field=models.DateField(blank=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='finish',
            field=models.DateTimeField(blank=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='identify',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор поля'),
        ),
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='start',
            field=models.DateTimeField(blank=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='fieldtext',
            name='identify',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор поля'),
        ),
        migrations.AlterField(
            model_name='fieldtext',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='fieldtextarea',
            name='identify',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор поля'),
        ),
        migrations.AlterField(
            model_name='fieldtextarea',
            name='textarea',
            field=models.TextField(blank=True, verbose_name='Большой текст'),
        ),
        migrations.AlterField(
            model_name='step',
            name='next_step',
            field=models.IntegerField(blank=True, default=999, verbose_name='id следующего этапа'),
        ),
    ]
