# Generated by Django 3.2.5 on 2023-06-06 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_for_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kostage',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Название этапа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kostage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Кто создал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintableko',
            name='stages',
            field=models.ManyToManyField(related_name='base', to='api_for_front.KoStage', verbose_name='Список Этапов'),
        ),
        migrations.AlterField(
            model_name='kostage',
            name='text',
            field=models.ManyToManyField(blank=True, to='api_for_front.FieldText', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='kostage',
            name='textarea',
            field=models.ManyToManyField(blank=True, to='api_for_front.FieldTextarea', verbose_name='Большой текст'),
        ),
        migrations.AlterField(
            model_name='maintableko',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название проекта'),
        ),
    ]
