# Generated by Django 3.2.5 on 2023-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0002_maintableko_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintableko',
            name='stages',
            field=models.ManyToManyField(related_name='base', to='api_for_front.KoStage', verbose_name='Список Этапов'),
        ),
    ]
