# Generated by Django 3.2.5 on 2023-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0003_auto_20230719_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddate',
            name='name_field',
            field=models.CharField(default='Дата', max_length=255, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='name_field',
            field=models.CharField(default='Начало-Конец время', max_length=255, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='fieldtext',
            name='name_field',
            field=models.CharField(default='Текст', max_length=255, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='fieldtextarea',
            name='name_field',
            field=models.CharField(default='Большой текс', max_length=255, verbose_name='Тип поля'),
        ),
    ]
