# Generated by Django 3.2.5 on 2023-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0003_auto_20230606_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='finish',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='fieldstartfinishtime',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
