# Generated by Django 3.2.5 on 2023-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0003_alter_maintableko_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kostage',
            name='text',
            field=models.ManyToManyField(blank=True, to='api_for_front.FieldText', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='kostage',
            name='textarea',
            field=models.ManyToManyField(blank=True, to='api_for_front.FieldTextarea', verbose_name='Большой текст'),
        ),
    ]
