# Generated by Django 3.2.5 on 2023-07-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0004_auto_20230719_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddate',
            name='link_step',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='step_date', to='api_for_front.step', verbose_name='связь с этапом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldstartfinishtime',
            name='link_step',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='step_f_s_time', to='api_for_front.step', verbose_name='связь с этапом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtext',
            name='link_step',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='step_text', to='api_for_front.step', verbose_name='связь с этапом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtextarea',
            name='link_step',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='step_textarea', to='api_for_front.step', verbose_name='связь с этапом'),
            preserve_default=False,
        ),
    ]
