# Generated by Django 3.2.5 on 2023-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0005_auto_20230720_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название этапа'),
        ),
    ]
