# Generated by Django 3.2.5 on 2023-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0006_alter_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date_end',
            field=models.DateTimeField(blank=True, verbose_name='Дата конца работы'),
        ),
        migrations.AlterField(
            model_name='step',
            name='date_start',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала работы'),
        ),
    ]
