# Generated by Django 3.2.5 on 2023-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0008_alter_step_structure_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца работы'),
        ),
        migrations.AlterField(
            model_name='step',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
