# Generated by Django 3.2.5 on 2023-07-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0009_auto_20230720_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.PositiveIntegerField(verbose_name='начало связи')),
                ('end_id', models.PositiveIntegerField(verbose_name='конец связи')),
                ('description', models.CharField(max_length=255, verbose_name='описания')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='цвет')),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='next_step',
        ),
        migrations.AddField(
            model_name='mainproject',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создание'),
        ),
        migrations.AddField(
            model_name='mainproject',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца работы'),
        ),
        migrations.AddField(
            model_name='mainproject',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AddField(
            model_name='step',
            name='what_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_for_front.mainproject', verbose_name='id проекта'),
            preserve_default=False,
        ),
    ]
