# Generated by Django 3.2.5 on 2023-07-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_for_front', '0011_mainproject_last_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproject',
            old_name='stages',
            new_name='id_steps',
        ),
        migrations.RemoveField(
            model_name='step',
            name='structure_step',
        ),
        migrations.RemoveField(
            model_name='step',
            name='user',
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='step',
            name='what_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_for_front.mainproject', verbose_name='id проекта'),
        ),
        migrations.CreateModel(
            name='StepTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название этапа')),
                ('structure_step', models.JSONField(default=dict, verbose_name='структура этапа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
        ),
    ]
