# Generated by Django 3.2.5 on 2023-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0012_auto_20230722_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steptemplates',
            old_name='structure_step',
            new_name='structure',
        ),
        migrations.AddField(
            model_name='steptemplates',
            name='structure_for_create',
            field=models.JSONField(default=dict, verbose_name='структура для создания этапа'),
        ),
    ]
