# Generated by Django 3.2.5 on 2023-07-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0013_auto_20230722_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproject',
            name='id_steps',
            field=models.ManyToManyField(blank=True, related_name='base', to='api_for_front.Step', verbose_name='Список Этапов'),
        ),
        migrations.AlterField(
            model_name='step',
            name='what_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_for_front.mainproject', verbose_name='id проекта'),
        ),
    ]
