# Generated by Django 3.2.5 on 2023-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0014_auto_20230722_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproject',
            name='structure_project',
            field=models.JSONField(default=dict, verbose_name='структура проекта'),
        ),
        migrations.AlterField(
            model_name='step',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
    ]
