# Generated by Django 3.2.5 on 2023-08-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_for_front', '0015_auto_20230726_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproject',
            name='id_steps',
        ),
        migrations.AddField(
            model_name='step',
            name='templates_schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='copy_steps', to='api_for_front.steptemplates', verbose_name='Схема для создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproject',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='mainproject',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='последние изменения'),
        ),
        migrations.AlterField(
            model_name='steptemplates',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
    ]
