# Generated by Django 3.2.5 on 2023-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0016_auto_20230804_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplates',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название схемы'),
        ),
    ]
