# Generated by Django 3.2.5 on 2023-08-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0018_auto_20230804_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='what_project',
            new_name='project_id',
        ),
    ]
