# Generated by Django 4.0 on 2023-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0019_rename_what_project_step_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='корды и размеры для этапа'),
        ),
    ]
