# Generated by Django 4.0 on 2023-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0021_remove_steptemplates_schema_for_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='metadata',
            field=models.JSONField(verbose_name='корды и размеры для этапа'),
        ),
    ]
