# Generated by Django 4.0 on 2023-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0023_alter_steptemplates_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproject',
            name='structure_project',
        ),
        migrations.AddField(
            model_name='steptemplates',
            name='example_metadata',
            field=models.JSONField(default=dict, verbose_name='мета данные'),
        ),
    ]
