# Generated by Django 4.0 on 2023-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0024_remove_mainproject_structure_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplates',
            name='example_metadata',
            field=models.JSONField(verbose_name='мета данные'),
        ),
    ]
