# Generated by Django 4.0 on 2023-09-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0025_alter_steptemplates_example_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.JSONField(verbose_name='поле')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_for_front.step', verbose_name='связь с этапом')),
            ],
            options={
                'verbose_name': 'StepField',
                'verbose_name_plural': 'StepFields',
                'db_table': 'StepFields',
            },
        ),
    ]
