# Generated by Django 4.0 on 2023-09-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0027_alter_fields_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='SF_time',
        ),
        migrations.RemoveField(
            model_name='step',
            name='date',
        ),
        migrations.RemoveField(
            model_name='step',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='step',
            name='text',
        ),
        migrations.RemoveField(
            model_name='step',
            name='textarea',
        ),
        migrations.AddField(
            model_name='step',
            name='placement',
            field=models.JSONField(default=dict, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='step',
            name='templates_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api_for_front.steptemplates', verbose_name='Схема для создания'),
        ),
        migrations.AlterModelTable(
            name='step',
            table='Steps',
        ),
    ]
