# Generated by Django 4.0 on 2023-09-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0028_alter_step_options_remove_step_sf_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='filed',
            field=models.JSONField(verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api_for_front.step', verbose_name='Связь с этапом'),
        ),
    ]
