# Generated by Django 4.0 on 2023-09-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0029_alter_fields_filed_alter_fields_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptemplates',
            name='example_metadata',
        ),
    ]
