# Generated by Django 4.0 on 2023-09-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0030_remove_steptemplates_example_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='StepFields',
        ),
    ]
