# Generated by Django 4.0 on 2023-09-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0031_rename_fields_stepfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepfields',
            old_name='filed',
            new_name='field',
        ),
    ]
