# Generated by Django 4.0 on 2023-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0032_rename_filed_stepfields_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='placement',
            field=models.JSONField(verbose_name='Расположение'),
        ),
    ]
