# Generated by Django 4.0 on 2023-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0033_alter_step_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksstep',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='описания'),
        ),
    ]
