# Generated by Django 4.0 on 2023-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0034_alter_linksstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksstep',
            name='data',
            field=models.JSONField(default={}, verbose_name='id фронта'),
            preserve_default=False,
        ),
    ]
