# Generated by Django 4.0 on 2023-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0036_step_noda_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='noda_front',
            field=models.CharField(max_length=255, verbose_name='id ноды фронта'),
        ),
    ]
