# Generated by Django 4.0 on 2023-10-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api_for_front', '0038_step_users_inspecting_step_users_look_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='users_responsible',
        ),
        migrations.AddField(
            model_name='step',
            name='responsible_persons_scheme',
            field=models.JSONField(blank=True, default=dict, verbose_name='Схема ответственных лиц'),
        ),
        migrations.AddField(
            model_name='step',
            name='users_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to='auth.user', verbose_name='Тот кто ответственен'),
        ),
    ]
