# Generated by Django 4.0 on 2023-10-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0039_remove_step_users_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='link_main_project',
        ),
    ]
