# Generated by Django 4.0 on 2023-10-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0040_remove_projectfiles_link_main_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='StepFiles',
        ),
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='StepImages',
        ),
    ]
