# Generated by Django 4.0 on 2023-10-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0041_rename_projectfiles_stepfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfiles',
            name='link_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_file', to='api_for_front.stepfiles', verbose_name='связь с полем'),
            preserve_default=False,
        ),
    ]
