# Generated by Django 4.0 on 2023-10-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0042_stepfiles_link_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfiles',
            name='link_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_file', to='api_for_front.stepfields', verbose_name='связь с полем'),
        ),
    ]
