# Generated by Django 4.0 on 2023-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0043_alter_stepfiles_link_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfiles',
            name='path_file',
            field=models.FileField(upload_to='file/%Y/%m-%d/', verbose_name='Файл'),
        ),
    ]
