# Generated by Django 4.0 on 2023-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0044_alter_stepfiles_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='responsible_persons_scheme',
            field=models.JSONField(blank=True, default={'users_editor': 0, 'users_inspecting': 0, 'users_look': []}, verbose_name='Схема ответственных лиц'),
        ),
    ]
