# Generated by Django 4.0 on 2023-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0046_step_active_step_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproject',
            name='active',
            field=models.BooleanField(default=False, verbose_name='В процессе'),
        ),
    ]
