# Generated by Django 4.0 on 2023-10-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0047_mainproject_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='project_id',
            new_name='project',
        ),
    ]
