# Generated by Django 4.0 on 2023-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0050_step_beginner_in_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproject',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название проекта'),
        ),
    ]
