# Generated by Django 4.0 on 2023-10-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api_for_front', '0054_remove_fieldstartfinishtime_link_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название схемы')),
                ('ste_fields_schema', models.JSONField(verbose_name='схема полей этапа')),
                ('responsible_persons_scheme', models.JSONField(blank=True, default={'users_editor': '', 'users_inspecting': '', 'users_look': []}, verbose_name='Схема ответственных лиц')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'StepsSchema',
                'verbose_name_plural': 'StepsSchemas',
                'db_table': 'StepsSchema',
            },
        ),
        migrations.AlterField(
            model_name='step',
            name='templates_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api_for_front.stepsschema', verbose_name='Схема для создания'),
        ),
        migrations.DeleteModel(
            name='StepTemplates',
        ),
    ]
