# Generated by Django 4.0 on 2023-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0055_stepsschema_alter_step_templates_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='step',
            old_name='templates_schema',
            new_name='step_schema',
        ),
    ]
