# Generated by Django 4.0 on 2023-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0056_steptemplates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='beginner_in_project',
            new_name='first_in_project',
        ),
        migrations.AddField(
            model_name='step',
            name='last_in_project',
            field=models.BooleanField(default=False, verbose_name='Завершающий в проекте'),
        ),
        migrations.AddField(
            model_name='stepsschema',
            name='first_in_project',
            field=models.BooleanField(default=False, verbose_name='Начинающий в проекте'),
        ),
        migrations.AddField(
            model_name='stepsschema',
            name='last_in_project',
            field=models.BooleanField(default=False, verbose_name='Завершающий в проекте'),
        ),
    ]
