# Generated by Django 4.0 on 2023-10-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0058_rename_user_stepsschema_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepsschema',
            old_name='ste_fields_schema',
            new_name='step_fields_schema',
        ),
    ]
