# Generated by Django 4.0 on 2023-10-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0059_rename_ste_fields_schema_stepsschema_step_fields_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsschema',
            name='placement',
            field=models.JSONField(default={'1': 1}, verbose_name='Расположение'),
            preserve_default=False,
        ),
    ]
