# Generated by Django 4.0 on 2023-10-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api_for_front', '0060_stepsschema_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsschema',
            name='template_project',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id шаблона проекта'),
        ),
        migrations.CreateModel(
            name='TemplateMainProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название шаблона  проекта')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'TemplateMainProject',
                'verbose_name_plural': 'TemplatesMainProject',
                'db_table': 'TemplateMainProject',
            },
        ),
    ]
