# Generated by Django 4.0 on 2023-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0065_alter_steptemplates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepschema',
            name='noda_front',
            field=models.CharField(blank=True, max_length=255, verbose_name='id ноды фронта'),
        ),
        migrations.AlterField(
            model_name='stepschema',
            name='placement',
            field=models.JSONField(default=dict, verbose_name='Расположение'),
        ),
    ]
