# Generated by Django 4.0 on 2023-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0066_alter_stepschema_noda_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steptemplates',
            old_name='templates',
            new_name='schema',
        ),
    ]
