# Generated by Django 4.0 on 2023-10-18 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0067_rename_templates_steptemplates_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemainproject',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создание'),
            preserve_default=False,
        ),
    ]
