# Generated by Django 4.0 on 2023-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0068_templatemainproject_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemainproject',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название шаблона проекта'),
        ),
    ]
