# Generated by Django 4.0 on 2023-10-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api_for_front', '0069_alter_templatemainproject_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainProject',
            new_name='MainKo',
        ),
        migrations.RenameModel(
            old_name='TemplateMainProject',
            new_name='TemplateMainKo',
        ),
        migrations.AlterModelOptions(
            name='mainko',
            options={'verbose_name': 'MainKo', 'verbose_name_plural': 'MainKo'},
        ),
        migrations.AlterModelOptions(
            name='templatemainko',
            options={'verbose_name': 'TemplateMainKo', 'verbose_name_plural': 'TemplatesMainKo'},
        ),
        migrations.AlterModelTable(
            name='mainko',
            table='MainKo',
        ),
        migrations.AlterModelTable(
            name='templatemainko',
            table='TemplateMainKo',
        ),
    ]
