# Generated by Django 4.0 on 2023-10-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0070_rename_mainproject_mainko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepimages',
            name='link_main_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_for_front.templatemainko', verbose_name='Объект привязки'),
        ),
    ]
