# Generated by Django 4.0 on 2023-10-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api_for_front', '0072_steptemplates_template_main_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptemplates',
            name='template_main_project',
        ),
        migrations.AddField(
            model_name='mainko',
            name='template_ko',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ko', to='api_for_front.templatemainko', verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainko',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='steptemplates',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='templatemainko',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Кто создал'),
        ),
    ]
