# Generated by Django 4.0 on 2023-10-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0073_remove_steptemplates_template_main_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_for_front.mainko', verbose_name='id проекта'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api_for_front.stepschema', verbose_name='Схема для создания'),
        ),
    ]
