# Generated by Django 4.0 on 2023-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0074_alter_step_project_alter_step_step_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksstep',
            name='in_template',
            field=models.BooleanField(default=True, verbose_name='Относится ли к шаблону'),
        ),
        migrations.AddField(
            model_name='linksstep',
            name='project_id',
            field=models.PositiveIntegerField(null=True, verbose_name='id шаблона проекта'),
        ),
        migrations.AddField(
            model_name='templatemainko',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Законченность'),
        ),
    ]
