# Generated by Django 4.0 on 2023-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0075_linksstep_in_template_linksstep_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksstep',
            name='data',
            field=models.JSONField(default=dict, verbose_name='id фронта'),
        ),
    ]
