# Generated by Django 4.0 on 2023-10-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0076_alter_linksstep_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='responsible_persons_scheme',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step_schema',
        ),
    ]
