# Generated by Django 4.0 on 2023-11-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_for_front', '0081_step_schema_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepschema',
            name='template_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps_schemas', to='api_for_front.templatemainko', verbose_name='Шаблона проекта'),
        ),
    ]
