# Generated by Django 4.0 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0004_userprofile_description_userprofile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='Шеф'),
        ),
    ]
