# Generated by Django 4.0 on 2023-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0006_userprofile_chief_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(max_length=255, verbose_name='отчество'),
        ),
    ]
